# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=50)),
                ('host_port', models.CharField(max_length=10)),
                ('latest_version', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('is_online', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('lastupdatetime', models.TimeField()),
            ],
        ),
    ]
